version: 0.0 

os: linux 
files:
  - source: build/*
destination: /home/ubuntu/sns-v1
BeforeInstall:
  - location: scripts/before_install.sh
AfterInstall:
  - location: scripts/after_install.sh
ApplicationStart:
  - location: scripts/start_server.sh
ApplicationStop:
  - location: scripts/stop_server.sh
