version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing node
      - npm install
  build: 
    commands:
      - echo Start building frontend
      - npm run-script build
  post_build:
    commands: 
      - echo Build completed

artifacts:
  files: 
    - 'build/*'
    - 'scripts/*'
    - 'package.json'
    - 'package-lock.json'
    - 'appspec.yml'